spring.application.name=book-api

spring.datasource.url=jdbc:postgresql://localhost:5432/bookdb
spring.datasource.username=bookuser
spring.datasource.password=bookpass

spring.jooq.sql-dialect=POSTGRES
spring.flyway.enabled=true
